### ISSUE TITLE
Non-minified JS 

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [RoelN/c64css3#1]
Hi,

really great work!

Could you also provide a not minified version of the javascript?

Thanks!

**Comment by RoelN** [comment]
Hi, this thing is completely JavaScript-free :-) I think you're referring to [Prefix Free](https://leaverou.github.io/prefixfree/), which is only used to add prefixes. You can find the unminified version on their site!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah I see, thank you!!
